name: Release
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml
    secrets: inherit

  changesets:
    name: Changesets
    needs: check
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          submodules: true

      - name: Setup and install
        uses: ./.github/actions/setup-and-install

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          title: 'Release'
          commit: 'chore: version packages'
          version: pnpm changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
